app:
  debug: falsem
  name: hiraexam
  version: beta-0.02
database:
  engine: postgresql
  host: localhost
  name: sman2cikpusexam
  password: hirakamucatodevsql
  port: 5432
  user: postgres
logging:
  file: logs/app.log
  level: INFO
ongoing-exam: true
secret_key: movingforbrightfuture
server:
  host: 0.0.0.0
  port: 5000
